#!/usr/bin/env node

/**
 * Testing Utilities for Worker5 Breakthrough Testing
 * Auto-generated by Worker2 Technical Support System
 */

class TestingUtils {
  static async measureExecutionTime(fn) {
    const start = Date.now();
    const result = await fn();
    const time = Date.now() - start;
    return { result, executionTime: time };
  }
  
  static async validateCastleData(castle) {
    const required = ['id', 'castleName', 'country', 'location', 'architecturalStyle', 'yearBuilt'];
    const missing = required.filter(field => !castle[field]);
    return { isValid: missing.length === 0, missingFields: missing };
  }
  
  static generateTestReport(testName, results) {
    return {
      testName,
      timestamp: new Date().toISOString(),
      results,
      summary: {
        total: results.length,
        passed: results.filter(r => r.status === 'passed').length,
        failed: results.filter(r => r.status === 'failed').length
      }
    };
  }
}

module.exports = TestingUtils;
